[package]
name = "oval"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = { version = "0.10.1", features = ["pratt"] }
ariadne = "0.5.1"
eyre = "0.6.12"
string-interner = "0.19.0"
parking_lot = "0.12.3"
paste = "1.0.15"