[package]
name = "oval"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []
binary-build = ["dep:eyre", "std"]


[[bin]]
name = "oval"
required-features = ["binary-build"]

[dependencies]
eyre = { version = "0.6.12", optional = true }
cow-array = { version = "*", path = "../cow-array" }
thiserror = "2.0.12"

ariadne = "0.5.1"
hashbrown = "0.15.4"
parking_lot = "0.12.4"
paste = "1.0.15"

